### PR TITLE
Move class to widget

### PR DESCRIPTION
**Pull request by rgs258**
The bootstrap_form tag in the popular django-bootstrap4 package will add a form-control class to the div of a form field. With a hard coded class in the templates, this results in two class attributes which is not allowed.

This change moves the class to the widget. This allows the widget to do all the class inserting and avoid creating duplicate class attributes on the div.

### CODE REVIEW

**Review by AltusBarry — CHANGES_REQUESTED** [review]
They @rgs258 this seems to contain more than just bootstrap package support. Perhaps split the PR?

**Comment by rgs258** [comment]
@AltusBarry yeah, after a couple months, I just started making changes and going for it on this branch.

I have no bandwidth for this work at the moment, but if there is a sincere will to review the PR going forward, then I'll try to find some time to clean it up and factor it properly. 

Please let me know how to proceed.

**Comment by rgs258** [comment]
I just want to add that I know how hard it is to manage a project, and don't fault you or anyone else for letting the PRs slip. I am very thankful for that this project exists, and any time you choose to give to it is very appreciated.

**Comment by AltusBarry** [comment]
@rgs258 We are gearing up to get a new release out there with a bunch of the quality of life PRs we already see open on this project. So from my side, I'd say now is the best time to have an open PR around here. :smile:

**Comment by thibaudcolas** [comment]
🤦  I didn’t intend to close this, and now I can’t reopen it because I deleted the base branch. If you’d like to reopen this please go ahead.

**Pull request closed without merging**
