### PR TITLE
Feature Request: Add actions in recaptcha v3 widget

### LINKED ISSUE #209: Adding actions in ReCaptchaV3 widget
Hello, 
I would like at change the default [action](https://developers.google.com/recaptcha/docs/v3#actions) for reCAPTCHA v3.  Default actions is 
` grecaptcha.execute('{{ public_key }}', {action: 'form'})`
I made the following changes. Added additional parameter action to  `ReCaptchaV3` widget and  passing it to context
```
class ReCaptchaV3(ReCaptchaBase):
    template_name = "captcha/widget_v3.html"

    def __init__(self, api_params=None, action="form", *args, **kwargs):
        super(ReCaptchaV3, self).__init__(
            api_params=api_params, *args, **kwargs
        )
        self.action = action

    def get_context(self, name, value, attrs):
        context = super(ReCaptchaV3, self).get_context(name, value, attrs)
        context.update({'action': self.action})
        return context
```
and js_v3.html
` grecaptcha.execute('{{ public_key }}', {action: '{{action}}'})`

It's working fine for me. I don't have much data in admin panel yet to tell more about actions. Can you please add similar functionality or shall I make a pull request if you think this changes wont make any issues?

### PR DESCRIPTION
**Pull request by alexrobertson-muckrack**
Replaces #233

> Closes #209 @binoyudayan did all of the work but I'm assuming was waiting for a response on the issue before creating a PR.
> This would be a nice feature providing [action support](https://developers.google.com/recaptcha/docs/v3#actions)
> 
> Which from the docs has the benefits of:
> 
> A detailed break-down of data for your top ten actions in the admin console
> Adaptive risk analysis based on the context of the action, because abusive behavior can vary.

Resolves a merge conflict in the original PR

### CODE REVIEW

**Review by Andrew-Chen-Wang — DISMISSED** [review]

**Comment by Andrew-Chen-Wang** [comment]
thanks mint error tho

**Comment by alexrobertson-muckrack** [comment]
@Andrew-Chen-Wang Can you clarify what you mean by "mint error"?

**Comment by Andrew-Chen-Wang** [comment]
sorry lint error*

**Comment by alexrobertson-muckrack** [comment]
It looks like a problem with the build process

```
build attempt 1...
    => error
    [INFO] Installing environment for https://github.com/pycqa/isort.
    [INFO] Once installed this environment will be reused.
    [INFO] This may take a few minutes...
    An unexpected error has occurred: CalledProcessError: command: ('/pc/clone/wvVSBsjfSEmrVJ2f-s2wow/py_env-python3/bin/python', '-mpip', 'install', '.')
    return code: 1
    stdout:
        Processing /pc/clone/wvVSBsjfSEmrVJ2f-s2wow
          Installing build dependencies: started
          Installing build dependencies: finished with status 'done'
          Getting requirements to build wheel: started
          Getting requirements to build wheel: finished with status 'done'
          Preparing metadata (pyproject.toml): started
          Preparing metadata (pyproject.toml): finished with status 'error'
    stderr:
          error: subprocess-exited-with-error
      
          × Preparing metadata (pyproject.toml) did not run successfully.
          │ exit code: 1
          ╰─> [17 lines of output]
              Traceback (most recent call last):
                File "/pc/clone/wvVSBsjfSEmrVJ2f-s2wow/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                  main()
                File "/pc/clone/wvVSBsjfSEmrVJ2f-s2wow/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                  json_out['return_val'] = hook(**hook_input['kwargs'])
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/pc/clone/wvVSBsjfSEmrVJ2f-s2wow/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
                  return hook(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/tmp/pip-build-env-ubgl9gzj/overlay/lib/python3.11/site-packages/poetry/core/masonry/api.py", line 41, in prepare_metadata_for_build_wheel
                  poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/tmp/pip-build-env-ubgl9gzj/overlay/lib/python3.11/site-packages/poetry/core/factory.py", line 58, in create_poetry
                  raise RuntimeError("The Poetry configuration is invalid:\n" + message)
              RuntimeError: The Poetry configuration is invalid:
                - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
          
              [end of output]
      
          note: This error originates from a subprocess, and is likely not a problem with pip.
        error: metadata-generation-failed
    
        × Encountered error while generating package metadata.
        ╰─> See above for output.
    
        note: This is an issue with the package mentioned above, not pip.
        hint: See above for details.
    Check the log at /pc/pre-commit.log
build attempt 2...
    => error
    [INFO] Installing environment for https://github.com/pycqa/isort.
    [INFO] Once installed this environment will be reused.
    [INFO] This may take a few minutes...
    An unexpected error has occurred: CalledProcessError: command: ('/pc/clone/wvVSBsjfSEmrVJ2f-s2wow/py_env-python3/bin/python', '-mpip', 'install', '.')
    return code: 1
    stdout:
        Processing /pc/clone/wvVSBsjfSEmrVJ2f-s2wow
          Installing build dependencies: started
          Installing build dependencies: finished with status 'done'
          Getting requirements to build wheel: started
          Getting requirements to build wheel: finished with status 'done'
          Preparing metadata (pyproject.toml): started
          Preparing metadata (pyproject.toml): finished with status 'error'
    stderr:
          error: subprocess-exited-with-error
      
          × Preparing metadata (pyproject.toml) did not run successfully.
          │ exit code: 1
          ╰─> [17 lines of output]
              Traceback (most recent call last):
                File "/pc/clone/wvVSBsjfSEmrVJ2f-s2wow/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                  main()
                File "/pc/clone/wvVSBsjfSEmrVJ2f-s2wow/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                  json_out['return_val'] = hook(**hook_input['kwargs'])
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/pc/clone/wvVSBsjfSEmrVJ2f-s2wow/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
                  return hook(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/tmp/pip-build-env-wthpukp9/overlay/lib/python3.11/site-packages/poetry/core/masonry/api.py", line 41, in prepare_metadata_for_build_wheel
                  poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/tmp/pip-build-env-wthpukp9/overlay/lib/python3.11/site-packages/poetry/core/factory.py", line 58, in create_poetry
                  raise RuntimeError("The Poetry configuration is invalid:\n" + message)
              RuntimeError: The Poetry configuration is invalid:
                - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
          
              [end of output]
      
          note: This error originates from a subprocess, and is likely not a problem with pip.
        error: metadata-generation-failed
    
        × Encountered error while generating package metadata.
        ╰─> See above for output.
    
        note: This is an issue with the package mentioned above, not pip.
        hint: See above for details.
    Check the log at /pc/pre-commit.log
```

This error is showing up in other recent PRs as well.

**Review by Andrew-Chen-Wang — APPROVED** [review]

**Comment by Andrew-Chen-Wang** [comment]
I don't think i have publishing permission.

**Comment by cbracco** [comment]
Looks like @Stormheg handled the last release? https://github.com/torchbox/django-recaptcha/releases/tag/3.0.0

**Comment by Stormheg** [comment]
I should be able to create a new release, like I did last year.

I do have some points I'd like to see addressed before releasing this:

1. The new 'action' argument to the ReCaptchaV3 widget is not documented. There should be documentation referencing the recaptcha docs on what this argument does and how to use it.
2. The [recaptcha docs](https://developers.google.com/recaptcha/docs/v3#actions) explicitly mention that we should  check the action name in the recaptcha response is the same as we expect. I don't see any code in this PR that does so. (not sure _why_ validating this is so important, but with such explicit mention of it there must be a good reason...)
3. Question: the action is now always specified with a default value of 'form'. Should this not be opt-in?

**Comment by Stormheg** [comment]
> As for point 3: the action was always required by the V3 API and the default has been form. This cannot be opt-in.

@alexrobertson-muckrack alright, thanks! I wasn't aware this has always been the default.

**Comment by cbracco** [comment]
@Stormheg any updates on when a release for this might go out? thanks again for merging 😄

**Comment by Stormheg** [comment]
@cbracco not sure when a new release will be out. Right now I'm waiting for review and feedback on #312 from another maintainer.

**Pull request merged**
