### PR TITLE
Add Indonesian (id) translations

### PR DESCRIPTION
**Pull request by kiraware**
Add Bahasa Indonesia support

### CODE REVIEW

**Review by kiraware — COMMENTED** [review]
Ready for review

**Comment by Andrew-Chen-Wang** [comment]
thank you tho the file doesn't seem complete, and it'd be great if you generated the mo file. thanks!

**Comment by kiraware** [comment]
Actually the .mo file is being ignored by `.gitignore`, that is the reason why i don't add it. My last commit add the .mo file. Thanks @Andrew-Chen-Wang for your response!

**Comment by Andrew-Chen-Wang** [comment]
oh thank you. sorry i'm mixing up oss projects

**Comment by kiraware** [comment]
Never mind @Andrew-Chen-Wang. Thanks for your fast response. Done revert the commit.

**Comment by Andrew-Chen-Wang** [comment]
sorry this is super annoying but can u revert that commit again and add back the mo file.

in the gitignore can u also remove the *.no entry. I see that the mo files are actually inside the package

**Comment by kiraware** [comment]
It's OK. Done @Andrew-Chen-Wang

**Review by Andrew-Chen-Wang — APPROVED** [review]

**Comment by Andrew-Chen-Wang** [comment]
thanks again!

**Pull request merged**
