### PR TITLE
Prepare v4 release

### PR DESCRIPTION
**Pull request by Stormheg**
Reasoning for new major release: we dropped support for unsupported Django and Python versions, which is a breaking change according to SemVer.

I'll fill in the release date once we actually release this.

### CODE REVIEW

**Comment by Stormheg** [comment]
https://github.com/torchbox/django-recaptcha/pull/311 should be merged before we release v4.

**Comment by Stormheg** [comment]
Hi @Andrew-Chen-Wang, any chance you are able to review this?

**Review by Andrew-Chen-Wang — DISMISSED** [review]

**Comment by Stormheg** [comment]
Thanks for reviewing @Andrew-Chen-Wang! I'll continue preparing the release when I have time.

Regarding your comment @alexrobertson-muckrack

>  If you're looking at a V4 release, you might drop the default for the V3 action.

I'm not sure what the benefit of this breaking change would be. [`action=form` has been the default for over 5 years.](https://github.com/torchbox/django-recaptcha/blame/ae9823595eee5c64313039f0aceb5d357aa706f4/captcha/templates/captcha/includes/js_v3.html#L5) 
I'm all for keeping the transition to v4 as smooth as possible. Is there a benefit I'm not aware of?

**Comment by alexrobertson-muckrack** [comment]
@Stormheg it would require users of V3 ReCAPTCHA to provide individual action values for their forms rather than assume they should all be grouped under the `form` action. Its not necessary but might promote better use of the V3 API.

**Comment by Stormheg** [comment]
Got it, any thoughts on this @Andrew-Chen-Wang?

**Comment by Andrew-Chen-Wang** [comment]
It just needs a guide inside of our docs (eg "Migrating to v4" section). Otherwise, many are using the defaults and providing a small hindrance to promote security is beneficial

**Comment by koutoftimer** [comment]
What left to be done for release to happen?

**Comment by Stormheg** [comment]
@koutoftimer don't worry, I'll get to this soon.

**Comment by koutoftimer** [comment]
I'm not sure, but it looks like closing issue about naming conflict will be beneficial #291

**Comment by Stormheg** [comment]
Marking as draft pending the renaming of the `captcha` namespace to `django_recaptcha`. See #317.

**Comment by enzedonline** [comment]
It would be useful to be able to add the action as an attribute (with `'form'` being the default value) and required score also (`settings.RECAPTCHA_REQUIRED_SCORE` being the default). It would allow distinguishing between usages (e.g. 'contact', 'signup' etc) and use specific scores in those places.
e.g. `ReCaptchaField(label="", widget=ReCaptchaV3(), action="signup", required_score=0.85)`

**Comment by Stormheg** [comment]
> It would be useful to be able to add the action as an attribute (with `'form'` being the default value) and required score also (`settings.RECAPTCHA_REQUIRED_SCORE` being the default). It would allow distinguishing between usages (e.g. 'contact', 'signup' etc) and use specific scores in those places. e.g. `ReCaptchaField(label="", widget=ReCaptchaV3(), action="signup", required_score=0.85)`

Hey @enzedonline, would you mind creating an issue out of this? From what I understand you want to be able to a specific required score for a specific type of form. This is an interesting idea and I'd love to discuss it further in a separate issue.

**Comment by Andrew-Chen-Wang** [comment]
> And finally; Actions are an optional feature in the reCAPTCHA v3 API. Wouldn't it be weird to make this required on our side?

It is for backwards compatibility as reCaptchav2 is still widely used I believe (yes, even with multi modal LLMs, they're expensive, and any form of captchas/locks are preventable to a certain degree); and imo, v2 is still very good.

But this is assuming the backwards compat is actually true. Please let me know.

**Review by Andrew-Chen-Wang — APPROVED** [review]
I will be busy next few days. I believe everything LGTM (besides the point above which requires further discussion if needed), and if not, I will be available to approve any new review requests immediately since there are a lot of breaking changes and plenty of patches may come ahead.

**Comment by Stormheg** [comment]
For all involved with this PR: I tried to create a release which should trigger the [`publish.yml` workflow](https://github.com/torchbox/django-recaptcha/blob/main/.github/workflows/publish.yml)  but this did not happen for some reason. I noticed the workflow is referencing a PyPI token which does not exist, so even if the workflow did trigger it wouldn't be able to upload to PyPI. First time we use this workflow, the previous release was uploaded manually by me but in the interest of security I no longer have the necessary access to do so.

I'm getting in touch with the relevant folks at Torchbox to sort out the PyPI situation as only they have access.

**Comment by enzedonline** [comment]
> > It would be useful to be able to add the action as an attribute (with `'form'` being the default value) and required score also (`settings.RECAPTCHA_REQUIRED_SCORE` being the default). It would allow distinguishing between usages (e.g. 'contact', 'signup' etc) and use specific scores in those places. e.g. `ReCaptchaField(label="", widget=ReCaptchaV3(), action="signup", required_score=0.85)`
> 
> Hey @enzedonline, would you mind creating an issue out of this? From what I understand you want to be able to a specific required score for a specific type of form. This is an interesting idea and I'd love to discuss it further in a separate issue.

@Stormheg Sorry, just saw this - added to the ideas list #320

**Comment by Stormheg** [comment]
I have been entrusted with PyPI access and have set up [Trusted Publishing](https://docs.pypi.org/trusted-publishers/) (https://github.com/torchbox/django-recaptcha/commit/791f833542fa89b05a0a4c6c70a6242c89853f15)

>"Trusted publishing" is our term for using the [OpenID Connect (OIDC)](https://openid.net/connect/) standard to exchange short-lived identity tokens between a trusted third-party service and PyPI. This method can be used in automated environments and eliminates the need to use username/password combinations or manually generated API tokens to authenticate with PyPI when publishing.

As a result, [v4.0.0 is now available on PyPI!](https://pypi.org/project/django-recaptcha/4.0.0/)

I'd like to thank all contributors and @Andrew-Chen-Wang for reviewing my PRs 🚀

**Pull request merged**
